Feature/task2
grisha-ctrl/shift pull request #2
Opened 2024-11-01 18:14 UTC by grisha-ctrl

не вмерживайте тк сейчас таск2 сравнивается с веткой таск1, тк таск 1 ещё не вмержен в мастер

2024-11-27 13:50 UTC, artsiom-kotau requested changes
В целом интересное решение, но в рамках задания является оверинжинирингом.
Использование аннотаций и рефлексии, может быть заменено стандартными подходами типа Фабрик. Собственно это задание и было расчитано на отрабатываение данного подхода. Каждая фигура создаётся с помощью определённой фабрики(ты заменил на аннотацию), валидация производиттся так же конкретным сервисом для каждой фигуры (у етбя отсутствует), вывод так же производится отдельным сервисом (у тебя этим занимаются частично модели).

2024-11-27 13:50 UTC, artsiom-kotau commented on task2/src/main/java/by/shift/task2/core/utils/DataReaderUtils.java
> +        FileData fileData = FileData.builder().build();
лишняя инициализация

2024-11-30 20:36 UTC, artsiom-kotau commented on task2/src/main/java/by/shift/task2/core/utils/DataReaderUtils.java
> +        FileData fileData = FileData.builder().build();
я бы попросил сделать
 "Каждая фигура создаётся с помощью определённой фабрики(ты заменил на аннотацию), валидация производиттся так же конкретным сервисом для каждой фигуры (у етбя отсутствует), вывод так же производится отдельным сервисом (у тебя этим занимаются частично модели)."

2024-12-06 17:39 UTC, grisha-ctrl commented on task2/src/main/java/by/shift/task2/core/utils/DataReaderUtils.java
> +        FileData fileData = FileData.builder().build();
добавил фабрику и валидацию, но вывод сделал через утилитный класс, тк не понимаю зачем добавлять сервис для этого, в случае несогласия пожалуйста объясни почему лучше иначе:)

2024-12-09 09:49 UTC, artsiom-kotau requested changes

2024-12-09 09:49 UTC, artsiom-kotau commented on task2/src/test/java/by/shift/task2/core/model/impl/TriangleTest.java
> +        Assertions.assertThat(actualCornerA).isEqualTo(cornerA);
не проходит тест

Expected :0.6435011087932843
Actual   :36.86989764584401

2024-12-09 09:49 UTC, artsiom-kotau commented on task2/src/main/java/by/shift/task2/core/utils/FigureOutputUtils.java
> +public class FigureOutputUtils {
по факту можно было сделать

интерфейс OutputService с методом write(String figureDescription)

и от него две имплементации
FileOutputService - тут в конструктор имя файла передаётся и выводится
ConsoleOutputService - тут просто system.out

и фабрику для создания сервиса по параметру запуска и всё

2024-12-09 19:04 UTC, grisha-ctrl commented on task2/src/main/java/by/shift/task2/core/utils/FigureOutputUtils.java
> +public class FigureOutputUtils {
переписал

2024-12-16 18:56 UTC, grisha-ctrl commented on task2/src/main/java/by/shift/task2/core/model/impl/Circle.java
> +    public String toString() {
доделал

2024-12-17 07:36 UTC, artsiom-kotau approved these changes
можно мержить

2024-12-17 20:13 UTC, merged