feature/task3/minesweeper
grisha-ctrl/shift pull request #3
Opened 2024-11-29 18:47 UTC by grisha-ctrl

2024-12-01 19:05 UTC, artsiom-kotau requested changes
Когда начинаю игру сразу с раставления флажка, мне в консоли пишет

2024-12-01T22:03:52.270+03:00  INFO 95015 --- [minesweeper-sb3] [nio-8080-exec-2] b.s.m.service.impl.DefaultGameService    : Создана игра с фиксированными параметрами
2024-12-01T22:03:53.311+03:00  INFO 95015 --- [minesweeper-sb3] [nio-8080-exec-3] b.s.m.service.impl.DefaultGameService    : Добавляет состояние флажка на указанной клетке, строка 1 столбец 1
2024-12-01T22:03:53.312+03:00  INFO 95015 --- [minesweeper-sb3] [nio-8080-exec-3] b.s.m.service.impl.DefaultGameService    : Вы победили

и дальше я не могу выполнить никак действий в игре

2024-12-09 21:02 UTC, grisha-ctrl commented on minesweeper/src/main/java/by/shift/minesweeper/service/impl/DefaultGameService.java
> +    private Game game;
не подумал о возможности создания нескольких рабочих игр одновременно, исправил недоработку

2024-12-09 21:03 UTC, grisha-ctrl commented on minesweeper/src/main/java/by/shift/minesweeper/service/impl/DefaultGameService.java
> +        game = new Game("1", 10, 10, 10);
в связи выноса сущности игры в проперти и неимением возможности создавать множество игр id теряет актуальность. Исправил

2024-12-09 21:03 UTC, grisha-ctrl commented on minesweeper/src/main/java/by/shift/minesweeper/service/impl/DefaultGameService.java
> +        log.info("Открываем клетку, строка {} столбец {}", row, col);
добавил

2024-12-09 21:04 UTC, grisha-ctrl commented on minesweeper/src/main/java/by/shift/minesweeper/service/impl/DefaultGameService.java
> +
добавил

2024-12-09 21:04 UTC, grisha-ctrl commented on minesweeper/src/main/java/by/shift/minesweeper/service/impl/DefaultGameService.java
> +        Random random = new Random();
исправил

2024-12-09 21:06 UTC, grisha-ctrl commented on minesweeper/src/main/java/by/shift/minesweeper/service/impl/DefaultGameService.java
> +        if (!isBoardInitialized()) {
она нужна чтобы не попасть на мину в самом начале игры, для этого добавление мин на борд происходит после нажатия на клетку или если первым действием идёт добавления флага

2024-12-10 09:30 UTC, artsiom-kotau commented on minesweeper/src/main/java/by/shift/minesweeper/service/impl/DefaultGameService.java
> +        Random random = new Random();
не исправил

2024-12-10 09:38 UTC, artsiom-kotau requested changes

2024-12-10 09:38 UTC, artsiom-kotau commented on minesweeper/src/main/java/by/shift/minesweeper/service/impl/DefaultGameService.java
> +        if (row < 0 || row >= game.getRows() || col < 0 || col >= game.getCols()){
этот код дублируется, возможно стоит его вынести в отдельный метод

2024-12-10 09:38 UTC, artsiom-kotau commented on minesweeper/src/main/java/by/shift/minesweeper/singleton/Cache.java
> +    private static final Map<String, Game> cacheRepository = new HashMap<>();
синхронизации досутпа к кешу нету

2024-12-10 09:38 UTC, artsiom-kotau commented on minesweeper/src/main/java/by/shift/minesweeper/service/impl/DefaultGameService.java
> +    private void checkWinCondition(Game game) {
Есть подозрение, что этот цикл лишний, обрати внимание на структуру класса Game
я думаю можно обойтись его полями

2024-12-10 13:05 UTC, grisha-ctrl commented on minesweeper/src/main/java/by/shift/minesweeper/service/impl/DefaultGameService.java
> +        Random random = new Random();
теперь исправил (надеюсь)

2024-12-10 13:05 UTC, grisha-ctrl commented on minesweeper/src/main/java/by/shift/minesweeper/service/impl/DefaultGameService.java
> +        if (row < 0 || row >= game.getRows() || col < 0 || col >= game.getCols()){
вынес

2024-12-10 13:05 UTC, grisha-ctrl commented on minesweeper/src/main/java/by/shift/minesweeper/singleton/Cache.java
> +    private static final Map<String, Game> cacheRepository = new HashMap<>();
сделал

2024-12-10 13:06 UTC, grisha-ctrl commented on minesweeper/src/main/java/by/shift/minesweeper/service/impl/DefaultGameService.java
> +    private void checkWinCondition(Game game) {
ты прав, у меня есть чем это заменить
переделал

2024-12-12 19:20 UTC, artsiom-kotau approved these changes
можно мержить

2024-12-13 07:55 UTC, merged